/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Link: typeof import('react-router').Link
  const Outlet: typeof import('react-router').Outlet
  const ReactViewTransition: typeof import('react').ViewTransition
  const RouterProvider: typeof import('react-router').RouterProvider
  const Suspense: typeof import('react').Suspense
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createBrowserRouter: typeof import('react-router').createBrowserRouter
  const createContext: typeof import('react').createContext
  const createMemoryRouter: typeof import('react-router').createMemoryRouter
  const createPortal: typeof import('react-dom').createPortal
  const createRef: typeof import('react').createRef
  const createRoot: typeof import('react-dom/client').createRoot
  const createRouterContext: typeof import('react-router').createContext
  const flushSync: typeof import('react-dom').flushSync
  const forwardRef: typeof import('react').forwardRef
  const isRouteErrorResponse: typeof import('react-router').isRouteErrorResponse
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const preconnect: typeof import('react-dom').preconnect
  const prefetchDNS: typeof import('react-dom').prefetchDNS
  const preinit: typeof import('react-dom').preinit
  const preinitModule: typeof import('react-dom').preinitModule
  const preload: typeof import('react-dom').preload
  const preloadModule: typeof import('react-dom').preloadModule
  const redirect: typeof import('react-router').redirect
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormStatus: typeof import('react-dom').useFormStatus
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMatches: typeof import('react-router').useMatches
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigation: typeof import('react-router').useNavigation
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRevalidator: typeof import('react-router').useRevalidator
  const useRouteError: typeof import('react-router').useRouteError
  const useRoutes: typeof import('react-router').useRoutes
  const useSearchParams: typeof import('react-router').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ReactNode, ComponentType, SVGProps, PropsWithChildren, Key, Ref, LazyExoticComponent, ReactElement } from 'react'
  import('react')
  // @ts-ignore
  export type { MiddlewareFunction, DataRouter, RouterState, RouteObject } from 'react-router'
  import('react-router')
}
