# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

defaults:
  run: 
    shell: bash

jobs:
  changelog:
    if: ${{ github.repository_owner === '435012357' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 获取分支的代码和提交记录
        uses: actions/checkout@v4

      # 设置Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instance dependencies
        run: npm install

      # 打包
      - name: Build Packages
        run: npm run build
        
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v2
        with:
          version: npm run version
          publish: npm exec changeset publish
          commit: '[ci] release'
          title: '[ci] release'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
